CREATE TABLE t_utils (login VARCHAR(50) NOT NULL PRIMARY KEY, mdp CHAR(255) NOT NULL, email VARCHAR(50) NOT NULL, type CHAR(1) NOT NULL, idAvatar INT, idLangue INT) ENGINE = InnoDB COLLATE utf8_general_ci;

CREATE TABLE t_avatarss (idAvatar` INT NOT NULL PRIMARY KEY AUTO_INCREMENT, nom VARCHAR(12) UNIQUE NOT NULL) ENGINE = InnoDB CHARSET=utf8 COLLATE utf8_general_ci;

ALTER TABLE t_utils ADD CONSTRAINT PK_idAvatar FOREIGN KEY (idAvatar) REFERENCES t_avatarss(idAvatar) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE t_utils ADD CONSTRAINT PK_idLangue FOREIGN KEY (idLangue) REFERENCES t_langues(idLangue) ON DELETE RESTRICT ON UPDATE RESTRICT;

CREATE TABLE t_langues (idLangue INT NOT NULL PRIMARY KEY AUTO_INCREMENT, nom VARCHAR(20) UNIQUE NOT NULL, nomDrapeau CHAR(6) UNIQUE NOT NULL, nomProperties CHAR(7) UNIQUE NOT NULL) ENGINE = InnoDB CHARSET=utf8 COLLATE utf8_general_ci;

INSERT INTO t_langues (nom, nomDrapeau) VALUES ('Français', 'FR.JPG');
INSERT INTO t_langues (nom, nomDrapeau) VALUES ('English', 'EN.JPG');