CREATE TABLE t_utils (login VARCHAR(50) NOT NULL PRIMARY KEY, mdp CHAR(255) NOT NULL, email VARCHAR(50) NOT NULL, type CHAR(1) NOT NULL, idAvatar INT) ENGINE = InnoDB COLLATE utf8_general_ci;

CREATE TABLE t_avatar (idAvatar` INT NOT NULL PRIMARY KEY AUTO_INCREMENT, nom VARCHAR(12) UNIQUE NOT NULL) ENGINE = InnoDB CHARSET=utf8 COLLATE utf8_general_ci;

ALTER TABLE t_utils ADD CONSTRAINT PK_idAvatar FOREIGN KEY (idAvatar) REFERENCES t_avatar(idAvatar) ON DELETE RESTRICT ON UPDATE RESTRICT;